flowcase:
  api_key: ${FLOWCASE_API_KEY}
  base-url: ${FLOWCASE_BASE_URL}
openai:
  api-key: ${OPENAI_API-KEY}
  model: gpt-4
  assistant-id: ${OPENAI_ASSISTANT-ID}
google:
  api-key: ${GOOGLE_API_KEY}
  model: gemini-1.5-pro-latest
