flowcase:
  apiKey: ${FLOWCASE_API_KEY}
  baseUrl: ${FLOWCASE_BASE_URL}
openai:
  apiKey: ${OPENAI_API_KEY}
  model: gpt-4
  assistantId: ${OPENAI_ASSISTANT_ID}
gemini:
    apiKey: ${GEMINI_API_KEY}
    model: gemini-2.5-pro-latest
