flowcase:
  apiKey: ${FLOWCASE_API_KEY}
  baseUrl: ${FLOWCASE_BASE_URL}
openai:
  apiKey: ${OPENAI_API_KEY}
  model: gpt-4
  assistantId: ${OPENAI_ASSISTANT_ID}
gemini:
  apiKey: ${GEMINI_API_KEY}
  model: gemini-1.5-pro-latest

spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5433/candidatematch
    username: candidatematch
    password: candidatematch123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000 # 5 minxutes
      connection-timeout: 20000 # 20 seconds
      schema: public
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Use 'validate' since you're using Liquibase
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 25
          order_inserts: true
          order_updates: true
    open-in-view: false
  sql:
    init:
      schema-locations: classpath:schema.sql

logging:
  level:
    no.cloudberries.candidatematch: DEBUG # Setter DEBUG-logging for din kode