flowcase:
  api_key: ${FLOWCASE_API_KEY}
  base-url: ${FLOWCASE_BASE_URL}
openai:
  api-key: ${OPENAI_API-KEY}
  model: gpt-4
  assistant-id: ${OPENAI_ASSISTANT-ID}
gemini:
    api-key: ${GEMINI_API_KEY}
    model: gemini-2.5-pro-latest
