spring:
  # Disable database auto-configuration for minimal startup
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration

# Minimal external service config with defaults
flowcase:
  apiKey: ${FLOWCASE_API_KEY:not-configured}
  baseUrl: ${FLOWCASE_BASE_URL:not-configured}

openai:
  apiKey: ${OPENAI_API_KEY:not-configured}
  model: gpt-4
  assistantId: ${OPENAI_ASSISTANT_ID:not-configured}

gemini:
  apiKey: ${GEMINI_API_KEY:not-configured}
  model: gemini-2.5-pro

embedding:
  enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always