services:
  postgres-local:
    image: pgvector/pgvector:pg15
    container_name: cloudberries-postgres-local
    restart: unless-stopped
    environment:
      POSTGRES_DB: candidatematch
      POSTGRES_USER: candidatematch
      POSTGRES_PASSWORD: candidatematch123
    ports:
      - "5433:5432" # Bruker port 5433 for å unngå konflikt med andre instillinger
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U candidatematch -d candidatematch"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    volumes:
      - postgres_local_data:/var/lib/postgresql/data

volumes:
  postgres_local_data:
    driver: local
