package no.cloudberries.candidatematch.infrastructure.integration.flowcase

import LiquibaseTestConfig
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import kotlinx.coroutines.delay
import kotlinx.coroutines.test.runTest
import no.cloudberries.candidatematch.infrastructure.repositories.ProjectRequestRepository
import no.cloudberries.candidatematch.service.embedding.FlowcaseCvTextFlattener
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.condition.EnabledIfSystemProperty
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.boot.test.mock.mockito.MockBean
import org.springframework.context.annotation.Import
import org.springframework.test.context.ActiveProfiles
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import java.nio.file.StandardOpenOption
import java.text.Normalizer
import java.time.Instant

@EnabledIfSystemProperty(named = "flowcase.manual", matches = "true")
@Import(LiquibaseTestConfig::class)
@ActiveProfiles("manualtest")
@SpringBootTest
class FlowcaseHttpClientIntegrationTest {
    @Autowired
    lateinit var flowcaseHttpClient: FlowcaseHttpClient
    @Autowired
    lateinit var flowcaseConfig: FlowcaseConfig

    @MockBean
    lateinit var projectRequestRepository: ProjectRequestRepository
    private val mapper = jacksonObjectMapper().registerModule(JavaTimeModule())
    private val prettyWriter = mapper.writerWithDefaultPrettyPrinter()

    data class ExportReport(
        val totalUsers: Int,
        val exportedCount: Int,
        val failedCount: Int,
        val outputRoot: Path,
    )

    @Test
    fun fetchSingleConsultant() {
        validateFlowcaseManualConfig()
        val userId = "682c529a17774f004390031f"
        val response = flowcaseHttpClient.fetchUserById(userId)
        assertNotNull(response)
        println(mapper.writerWithDefaultPrettyPrinter().writeValueAsString(response))
    }

    @Test
    fun fetchCompleteCv() {
        validateFlowcaseManualConfig()
        val userid = "682c529a17774f004390031f"
        val cvId = "682c529acf99685aed6fd592"
        val response = flowcaseHttpClient.fetchCompleteCv(
            userid,
            cvId
        )

        assertNotNull(response)

        println(mapper.writerWithDefaultPrettyPrinter().writeValueAsString(response))
    }

    @Test
    fun fetchAllConsultantWithCompleteCV() = runTest {
        validateFlowcaseManualConfig()
        fetchAndPrintConsultantsCvs()
    }
    @Test
    fun exportAllConsultantsToOllamaTrainingCatalog() = runTest {
        validateFlowcaseManualConfig()
        val report = exportCvsToLocalTrainingCatalog()
        assertTrue(
            report.exportedCount > 0,
            "Expected at least one exported CV, but exportedCount was 0. Check Flowcase credentials/connectivity."
        )
        println(
            """
            Export complete
            - Total users fetched: ${report.totalUsers}
            - Exported CV files: ${report.exportedCount}
            - Failed exports: ${report.failedCount}
            - Output folder: ${report.outputRoot}
            """.trimIndent()
        )
    }

    suspend fun fetchAndPrintConsultantsCvs() {
        flowcaseHttpClient.fetchAllUsers().flowcaseUserDTOs.forEach {
            delay(50)
            val cv = flowcaseHttpClient.fetchCompleteCv(
                it.userId,
                it.cvId
            )
            assertNotNull(cv)
            println(mapper.writerWithDefaultPrettyPrinter().writeValueAsString(cv))
        }
    }

    suspend fun exportCvsToLocalTrainingCatalog(): ExportReport {
        val repoRoot = locateRepoRoot()
        val outputRoot = repoRoot.resolve("ollama-models/data/flowcase-cv-catalog")
        val jsonDir = outputRoot.resolve("json")
        val textDir = outputRoot.resolve("text")
        val trainingDir = outputRoot.resolve("training")

        prepareDirectory(jsonDir)
        prepareDirectory(textDir)
        prepareDirectory(trainingDir)

        val users = flowcaseHttpClient.fetchAllUsers().flowcaseUserDTOs.sortedBy { it.name.lowercase() }
        val promptRows = mutableListOf<String>()
        val labelTemplateRows = mutableListOf<String>()
        val fewShotTemplate = StringBuilder().apply {
            appendLine("# Flowcase CV few-shot templates")
            appendLine("# Generated by FlowcaseHttpClientIntegrationTest.exportCvsToLocalTrainingCatalog")
            appendLine("# Fill in score/summary/strengths/improvements before adding selected examples to Modelfile")
            appendLine()
        }

        val failures = mutableListOf<Map<String, String>>()
        var exportedCount = 0

        users.forEachIndexed { index, user ->
            delay(75)
            runCatching {
                flowcaseHttpClient.fetchCompleteCv(
                    user.userId,
                    user.cvId
                )
            }.onSuccess { cv ->
                val baseFileName = buildBaseFileName(
                    ordinal = index + 1,
                    candidateName = cv.name,
                    userId = cv.userId,
                    cvId = cv.cvId
                )

                val jsonPath = jsonDir.resolve("$baseFileName.json")
                val textPath = textDir.resolve("$baseFileName.txt")

                val flattenedText = FlowcaseCvTextFlattener.toText(cv).trim()
                Files.writeString(
                    jsonPath,
                    prettyWriter.writeValueAsString(cv),
                    StandardCharsets.UTF_8,
                    StandardOpenOption.CREATE,
                    StandardOpenOption.TRUNCATE_EXISTING
                )
                Files.writeString(
                    textPath,
                    flattenedText,
                    StandardCharsets.UTF_8,
                    StandardOpenOption.CREATE,
                    StandardOpenOption.TRUNCATE_EXISTING
                )

                val prompt = buildEvaluationPrompt(
                    candidateName = cv.name,
                    cvText = flattenedText,
                    userId = cv.userId,
                    cvId = cv.cvId
                )
                promptRows += mapper.writeValueAsString(
                    mapOf(
                        "id" to baseFileName,
                        "userId" to cv.userId,
                        "cvId" to cv.cvId,
                        "candidateName" to cv.name,
                        "prompt" to prompt
                    )
                )
                labelTemplateRows += mapper.writeValueAsString(
                    mapOf(
                        "id" to baseFileName,
                        "labelStatus" to "TODO_MANUAL",
                        "prompt" to prompt,
                        "response" to mapOf(
                            "scorePercentage" to null,
                            "summary" to null,
                            "strengths" to emptyList<String>(),
                            "improvements" to emptyList<String>()
                        )
                    )
                )

                appendFewShotTemplate(
                    builder = fewShotTemplate,
                    sourceFileName = "json/$baseFileName.json",
                    cvText = flattenedText
                )

                exportedCount++
            }.onFailure { error ->
                failures += mapOf(
                    "userId" to user.userId,
                    "cvId" to user.cvId,
                    "name" to user.name,
                    "error" to (error.message ?: "Unknown error")
                )
            }
        }

        val promptJsonlPath = trainingDir.resolve("cv-evaluation-prompts.jsonl")
        val labelTemplateJsonlPath = trainingDir.resolve("cv-evaluation-label-template.jsonl")
        val fewShotTemplatePath = trainingDir.resolve("Modelfile-flowcase-cv-examples.txt")
        val manifestPath = trainingDir.resolve("export-manifest.json")

        Files.writeString(
            promptJsonlPath,
            promptRows.joinToString(separator = "\n", postfix = "\n"),
            StandardCharsets.UTF_8,
            StandardOpenOption.CREATE,
            StandardOpenOption.TRUNCATE_EXISTING
        )
        Files.writeString(
            labelTemplateJsonlPath,
            labelTemplateRows.joinToString(separator = "\n", postfix = "\n"),
            StandardCharsets.UTF_8,
            StandardOpenOption.CREATE,
            StandardOpenOption.TRUNCATE_EXISTING
        )
        Files.writeString(
            fewShotTemplatePath,
            fewShotTemplate.toString(),
            StandardCharsets.UTF_8,
            StandardOpenOption.CREATE,
            StandardOpenOption.TRUNCATE_EXISTING
        )
        Files.writeString(
            manifestPath,
            prettyWriter.writeValueAsString(
                mapOf(
                    "generatedAt" to Instant.now().toString(),
                    "sourceTest" to "FlowcaseHttpClientIntegrationTest.exportCvsToLocalTrainingCatalog",
                    "totalUsersFetched" to users.size,
                    "exportedCount" to exportedCount,
                    "failedCount" to failures.size,
                    "outputRoot" to outputRoot.toString(),
                    "jsonDirectory" to jsonDir.toString(),
                    "textDirectory" to textDir.toString(),
                    "trainingDirectory" to trainingDir.toString(),
                    "trainingFiles" to listOf(
                        promptJsonlPath.fileName.toString(),
                        labelTemplateJsonlPath.fileName.toString(),
                        fewShotTemplatePath.fileName.toString()
                    ),
                    "failures" to failures
                )
            ),
            StandardCharsets.UTF_8,
            StandardOpenOption.CREATE,
            StandardOpenOption.TRUNCATE_EXISTING
        )

        return ExportReport(
            totalUsers = users.size,
            exportedCount = exportedCount,
            failedCount = failures.size,
            outputRoot = outputRoot
        )
    }

    private fun locateRepoRoot(): Path {
        var current = Paths.get("").toAbsolutePath().normalize()
        while (true) {
            val hasOllamaModels = Files.isDirectory(current.resolve("ollama-models"))
            val hasCandidateMatch = Files.isDirectory(current.resolve("candidate-match"))
            if (hasOllamaModels && hasCandidateMatch) {
                return current
            }
            current = current.parent ?: break
        }
        throw IllegalStateException("Could not locate repository root containing ollama-models/ and candidate-match/")
    }

    private fun prepareDirectory(path: Path) {
        val file = path.toFile()
        if (file.exists()) {
            file.listFiles()?.forEach { child -> child.deleteRecursively() }
        }
        Files.createDirectories(path)
    }

    private fun buildBaseFileName(
        ordinal: Int,
        candidateName: String,
        userId: String,
        cvId: String
    ): String {
        val safeName = slugify(candidateName).ifBlank { "unknown-candidate" }
        val safeUserId = slugify(userId).take(16).ifBlank { "unknown-user" }
        val safeCvId = slugify(cvId).take(16).ifBlank { "unknown-cv" }
        return "%03d_%s_%s_%s".format(
            ordinal,
            safeName,
            safeUserId,
            safeCvId
        )
    }

    private fun slugify(value: String): String {
        val transliterated = value
            .replace("æ", "ae", ignoreCase = true)
            .replace("ø", "o", ignoreCase = true)
            .replace("å", "a", ignoreCase = true)

        val normalized = Normalizer.normalize(
            transliterated,
            Normalizer.Form.NFD
        ).replace("\\p{M}+".toRegex(), "")

        return normalized.lowercase()
            .replace("[^a-z0-9]+".toRegex(), "-")
            .trim('-')
    }

    private fun buildEvaluationPrompt(
        candidateName: String,
        cvText: String,
        userId: String,
        cvId: String
    ): String {
        val sanitizedText = sanitizeForMultilineBlock(cvText).take(12000)
        return """
            Vurder denne CV-en for et norsk teknologikonsulentselskap og returner kun gyldig JSON med feltene:
            scorePercentage, summary, strengths, improvements.

            Kandidat: $candidateName
            UserId: $userId
            CvId: $cvId

            CV-tekst:
            $sanitizedText
        """.trimIndent()
    }

    private fun appendFewShotTemplate(
        builder: StringBuilder,
        sourceFileName: String,
        cvText: String
    ) {
        val sanitizedText = sanitizeForMultilineBlock(cvText).take(6000)
        builder.appendLine("# From: $sourceFileName")
        builder.appendLine("MESSAGE user \"\"\"Evaluate this CV:")
        builder.appendLine()
        builder.appendLine(sanitizedText)
        builder.appendLine("\"\"\"")
        builder.appendLine()
        builder.appendLine("MESSAGE assistant \"\"\"{")
        builder.appendLine("  \"scorePercentage\": [SCORE_HERE],")
        builder.appendLine("  \"summary\": \"[SUMMARY_HERE]\",")
        builder.appendLine("  \"strengths\": [")
        builder.appendLine("    \"[STRENGTH_1]\",")
        builder.appendLine("    \"[STRENGTH_2]\",")
        builder.appendLine("    \"[STRENGTH_3]\"")
        builder.appendLine("  ],")
        builder.appendLine("  \"improvements\": [")
        builder.appendLine("    \"[IMPROVEMENT_1]\",")
        builder.appendLine("    \"[IMPROVEMENT_2]\",")
        builder.appendLine("    \"[IMPROVEMENT_3]\"")
        builder.appendLine("  ]")
        builder.appendLine("}\"\"\"")
        builder.appendLine()
    }

    private fun sanitizeForMultilineBlock(value: String): String {
        return value
            .replace("\"\"\"", "\"")
            .replace("\u0000", " ")
            .trim()
    }

    private fun validateFlowcaseManualConfig() {
        val baseUrl = flowcaseConfig.baseUrl.trim()
        val apiKey = flowcaseConfig.apiKey.trim()

        assertTrue(
            baseUrl.startsWith("http://") || baseUrl.startsWith("https://"),
            "FLOWCASE_BASE_URL must be set to a valid http(s) URL before running this manual test."
        )
        assertTrue(
            !baseUrl.contains("\${"),
            "FLOWCASE_BASE_URL is unresolved. Export it in your shell before running this manual test."
        )
        assertTrue(
            apiKey.isNotBlank(),
            "FLOWCASE_API_KEY must be set before running this manual test."
        )
        assertTrue(
            !apiKey.contains("\${"),
            "FLOWCASE_API_KEY is unresolved. Export it in your shell before running this manual test."
        )
    }
}