# .github/workflows/maven.yml

name: Java CI with Maven and Gemini PR Review

on:
  pull_request:
    # Kj칮rer kun n친r en pull request mot main opprettes eller oppdateres
    branches: [ "main" ]

jobs:
  build_and_review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      # --- Steg 1: Kode-oppsett ---
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Henter hele historikken for 친 kunne sammenligne branches

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # --- Steg 2: Bygg og test ---
      - name: Build and Test with Maven
        run: mvn -B verify --file pom.xml

      # --- Steg 3: Kall Gemini API for kode-review ---
      - name: Perform Code Review with Gemini
        if: ${{ success() }}
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          PROMPT_TEMPLATE=$(cat .github/prompts/pr_review_prompt.txt)
          CODE_DIFF=$(git diff origin/main...HEAD)
          
          # Bygg payload p친 en sikker m친te
          FULL_PROMPT="${PROMPT_TEMPLATE//\{diff\}/$CODE_DIFF}"
          JSON_PAYLOAD=$(jq -n --arg text_content "$FULL_PROMPT" \
            '{contents: [{parts: [{text: $text_content}]}]}')

          # Logikk for 친 pr칮ve p친 nytt (retry)
          MAX_ATTEMPTS=3
          RETRY_DELAY=5 # Sekunder
          for ((i=1; i<=MAX_ATTEMPTS; i++)); do
            echo "::notice::Fors칮k $i av $MAX_ATTEMPTS p친 친 kalle Gemini API..."
          
            # Bruk -w for 친 f친 http-status og body separat
            HTTP_RESPONSE=$(curl -s -w "%{http_code}" -X POST \
              "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:generateContent?key=$GEMINI_API_KEY" \
              -H "Content-Type: application/json" \
              -d "$JSON_PAYLOAD")
          
            HTTP_STATUS_CODE=${HTTP_RESPONSE: -3}
            GEMINI_RESPONSE=${HTTP_RESPONSE:0:${#HTTP_RESPONSE}-3}
          
            if [ "$HTTP_STATUS_CODE" -eq 200 ]; then
              echo "::notice::Suksess fra Gemini API."
              break # G친 ut av loopen ved suksess
            elif [ "$i" -lt "$MAX_ATTEMPTS" ]; then
              echo "::warning::Mottok HTTP status $HTTP_STATUS_CODE. Pr칮ver igjen om $RETRY_DELAY sekunder..."
              echo "API-respons: $GEMINI_RESPONSE"
              sleep $RETRY_DELAY
            else
              echo "::error::Feil fra Gemini API etter $MAX_ATTEMPTS fors칮k. HTTP status: $HTTP_STATUS_CODE"
              echo "$GEMINI_RESPONSE"
              exit 1
            fi
          done

          # Sjekk for feil i selve JSON-responsen
          if echo "$GEMINI_RESPONSE" | jq -e '.error' > /dev/null; then
            echo "::error::Gemini API returnerte en feilmelding:"
            echo "$GEMINI_RESPONSE"
            exit 1
          fi

          echo "$GEMINI_RESPONSE" | jq -r '.candidates[0].content.parts[0].text' > gemini_review.txt
          echo "Gemini-review lagret i gemini_review.txt"
      # --- Steg 4: Publiser review som en kommentar p친 Pull Requesten ---
      - name: Comment on Pull Request
        if: ${{ success() && github.event_name == 'pull_request' }}
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const review = fs.readFileSync('gemini_review.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### 游뱄 Gemini Code Review\n\n${review}`
            });
